// Comprehensive Placement-Oriented Skill List
export const availableSkills = [
  // --- Programming Languages ---
  "C",
  "C++",
  "Java",
  "Python",
  "JavaScript",
  "TypeScript",
  "Go",
  "Rust",
  "Kotlin",
  "Swift",
  "PHP",
  "Ruby",
  "SQL",
  "R",
  "MATLAB",
  "Shell Scripting",

  // --- Web Development ---
  "HTML",
  "CSS",
  "React.js",
  "Next.js",
  "Angular",
  "Vue.js",
  "Node.js",
  "Express.js",
  "Django",
  "Flask",
  "Spring Boot",
  "REST APIs",
  "GraphQL",
  "Bootstrap",
  "Tailwind CSS",

  // --- Databases & Data Management ---
  "MySQL",
  "PostgreSQL",
  "MongoDB",
  "Firebase",
  "Redis",
  "Oracle",
  "SQLite",
  "NoSQL",
  "Database Design",
  "Data Modeling",

  // --- Data Science & Analytics ---
  "Data Structures & Algorithms",
  "Machine Learning",
  "Deep Learning",
  "Artificial Intelligence",
  "Natural Language Processing",
  "Computer Vision",
  "Data Analysis",
  "Data Visualization",
  "Pandas",
  "NumPy",
  "Matplotlib",
  "Scikit-learn",
  "TensorFlow",
  "PyTorch",
  "Power BI",
  "Tableau",
  "Excel (Advanced)",

  // --- Cloud & DevOps ---
  "AWS",
  "Azure",
  "Google Cloud Platform",
  "CI/CD",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "Git",
  "GitHub",
  "GitLab",
  "Terraform",
  "Linux Administration",

  // --- Cybersecurity & Networking ---
  "Network Security",
  "Ethical Hacking",
  "Penetration Testing",
  "Information Security",
  "Cryptography",
  "Firewalls",
  "Wireshark",
  "Cyber Threat Analysis",

  // --- Mobile App Development ---
  "React Native",
  "Flutter",
  "Android Development",
  "iOS Development",
  "SwiftUI",
  "Jetpack Compose",

  // --- Mechanical / Civil / Electrical / Core Engineering ---
  "AutoCAD",
  "SolidWorks",
  "CATIA",
  "ANSYS",
  "MATLAB (Engineering)",
  "Embedded Systems",
  "IoT",
  "Arduino",
  "Raspberry Pi",
  "PLC Programming",
  "SCADA",
  "Electrical Circuit Design",
  "Power Systems",
  "Thermodynamics",
  "3D Modeling",
  "Revit",
  "STAAD Pro",

  // --- Soft Skills & Professional ---
  "Communication Skills",
  "Teamwork",
  "Problem Solving",
  "Critical Thinking",
  "Leadership",
  "Time Management",
  "Project Management",
  "Agile Methodology",
  "Scrum",
  "Presentation Skills",
  "Business Communication",
  "Public Speaking",

  // --- Additional Placement-Relevant Topics ---
  "Operating Systems",
  "Computer Networks",
  "DBMS",
  "OOP (Object Oriented Programming)",
  "System Design",
  "Software Engineering",
  "Aptitude",
  "Logical Reasoning",
  "Quantitative Analysis",
  "Competitive Programming",
];